# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 53e55307d60354f835683e45da044005d94595a4369375f6acd190f726525ae17d298674b794375cb46ddaa0f90a4d0f1a4b7e92fc45cd0469581cb233889e48

test:
  secret_key_base: b93e430f32ecdc414017e8b210d218d6926210e4be71d8c3458654fd076eabd2cc4157e8b572cfd90245c6423211eb3ce55b88b5b4bf2e0850085e6b66b05215

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
